from abc import ABC, abstractmethod
from src.model.alpha_metadata import AlphaMetadata
from src.model.alpha_status_code import AlphaStatusCode
from typing import Tuple


class ARBService(ABC):
    """
    Abstract base class for managing multiple AI agents and their interactions.
    """

    
    @abstractmethod
    async def chat(self, user_id: str, message: str) -> Tuple[AlphaMetadata, AlphaStatusCode]:
        """
        Process a message through the multi-agent system.
        
        Args:
            user_id: The user ID to process
            message: The input message to process
            
        Returns:
            Tuple[AlphaMetadata, AlphaStatusCode]: The response generated by the agent system
        """
        pass