confirmation_recognizer_agent_config:
  name: "Confirmation Recognizer Agent"
  task_description: "Confirmation Recognizer Agent is a service that recognizes the user's confirmation."
  llm_model: "qwen2.5:14b"


greeting_agent_config:
  name: "Greeting Agent"
  task_description: "Greeting Agent is a service that greets the user."
  llm_model: "qwen2.5:14b"


greeting_recognizer_agent_config:
  name: "Greeting Recognizer Agent"
  task_description: "Greeting Recognizer Agent is a service that recognizes the user's greeting."
  llm_model: "qwen2.5:14b"


report_calling_agent_config:
  name: "Report Calling Agent"
  task_description: "Report Calling Agent is a service that reports the user's calling."
  llm_model: "qwen2.5:14b"


ner_agent_config:
  name: "NER Agent"
  task_description: "NER Agent is a service that recognizes the user's NER."
  llm_model: "qwen2.5:14b"

removal_entity_detection_agent_config:
  name: "Removal Entity Detection Agent"
  task_description: "Removal Entity Detection Agent is a service that detects the user's removal entity."
  llm_model: "qwen2.5:14b"


abbreviation_recognizer_agent_config:
  top_k: 10
  num_workers: 2