nosql_config:
  conversation_path: "./data/nosql/historical_conversation.json"
  expired_time: 0.5 # hour

sql_config:
  aiml_mysql:
    server : 'localhost'
    database_name : 'SPU_AIML'
    username : 'leon.vn'
    password : 'leonvn@aiml2209#'
    host : '10.18.200.72'
    port : '3306'
    dbms_name : 'MySQL'

vector_db_config:
  top_k: 10
  num_workers: 2
  path_save:
    report: 
      semantic: "./data/vector_db/report_semantic.index"
      keyword: "./data/vector_db/report_keyword.pkl"
    entity: 
      semantic: "./data/vector_db/entity_semantic.index"
      keyword: "./data/vector_db/entity_keyword.pkl"
